### ISSUE TITLE
(BTA) Bugged silver door and silver bed not working

### ISSUE THREAD

**Issue by Eggmanplant** [LukeisStuff/bonusblocks#15]
Bugged silver door:
![2024-03-09_08 36 49](https://github.com/LukeisStuff/bonusblocks/assets/126160675/8d8929f6-0cb4-41b0-878f-5a7474e2d0ee)
I can't sleep on the silver bed

**Comment by LukeisStuff** [comment]
I cant do anything about the bed part because its hardcoded, and not sure about the door thing maybe just try reinstalling the mod

**Comment by Eggmanplant** [comment]
Ok, But the silver door is still bugged after reinstalling.

**Comment by Eggmanplant** [comment]
And I found another thing, so the Corroded Copper Fence is misspelled as "CorrodedCopper Fence"

**Comment by LukeisStuff** [comment]
OK the fence thing is fixed now I will look into the door issue

**Comment by LukeisStuff** [comment]
Door thing should be fixed as well next update hopefully
